FROM rust:latest

RUN apt update && apt install -y \
  lldb \
  wl-clipboard

RUN rustup component add \
  rust-analyzer \
  clippy \
  rustfmt

# Install cargo-binstall using the recommended method
RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

# Helix
ARG HELIX_VERSION=25.07.1
ENV HELIX_DIR=helix-$HELIX_VERSION-x86_64-linux
ENV HELIX_ARCHIVE=$HELIX_DIR.tar.xz

RUN curl -LO https://github.com/helix-editor/helix/releases/download/$HELIX_VERSION/$HELIX_ARCHIVE \
  && tar xf $HELIX_ARCHIVE
RUN mv $HELIX_DIR/hx $HELIX_DIR/runtime /usr/local/bin/
RUN rm -r $HELIX_ARCHIVE $HELIX_DIR
RUN ln -s /usr/bin/lldb /usr/bin/lldb-dap

CMD ["hx"]
